variables:

# Define stages for the pipeline
stages:
  - auth-service-install_dependencies
  - auth-service-run_tests

cache:
  paths:
    - node_modules # Cache node_modules to speed up subsequent jobs

install_dependencies_job:
  stage: auth-service-install_dependencies
  image: node:16 # Use an official Node.js image to install dependencies
  tags:
    - docker
  script:
    # Navigate to the backend/auth-service directory and install dependencies
    - cd backend/auth-service # Change directory to your auth-service
    - npm install # Install dependencies
  except:
    - tags # Exclude this job from running when triggered by tags (optional)

run_tests_job:
  stage: auth-service-run_tests
  image: node:16 # Use the same Node.js image to run Jest tests
  tags:
    - docker
  script:
    # Navigate to the auth-service directory and run the tests using Jest
    - cd backend/auth-service # Change directory to the auth-service
    - npm run test # Run Jest tests (ensure Jest is configured in package.json)
